### ISSUE TITLE
Hardware maintenance work

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/PRM#1]
### Todo

- [x] swap the satellite boxes for IM.
- [x] check the spectra before/after the work

**Comment by etoal83** [comment]
Satellite box replacement has done. >> [klog #8912](http://klog.icrr.u-tokyo.ac.jp/osl/?r=8912)
The spectrum measurement shows improvement of the noise level at high frequencies as expected.

**Comment by MiyoKouseki** [comment]
Can I close this issue?

**Comment by YoshinoriFujii** [comment]
Yes, please go ahead. For the others as well.
After that campaign, we will have to launch new issues maybe.. like HPCD replacement for PRM TM-stage etc..
